name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
author: games647
version: ${project.version}
description: ${project.description}
website: ${project.url}
softdepend:
    - mcMMO
    - Vault
    - SimpleClans
    - InSigns
    - Essentials
    - Factions
    - Jobs
    - Heroes
    - uSkyBlock

commands:
  sidebar:
    aliases: [scoreboardstats, side, ss, sb, board]

permissions:
  scoreboardstats.admin:
    default: op
    children:
      scoreboardstats.reload: true
      scoreboardstats.sign: true
      scoreboardstats.use: true
      scoreboardstats.hide: true
  scoreboardstats.member:
    default: true
    children:
      scoreboardstats.use: true
      scoreboardstats.sign: true
      scoreboardstats.hide: true
  scoreboardstats.use:
    description: ''
  scoreboardstats.sign:
    description: ''
  scoreboardstats.reload:
    description: ''
  scoreboardstats.hide:
    description: ''